### ISSUE TITLE
Arreglos en la clase Printer.

### ISSUE THREAD

**Issue by Juan-Weyrauch** [Juan-Weyrauch/Proyecto_Pokemon#34]
La clase "Printer" actualmente tiene ~480 líneas. Creo que hablo por todos que está siendo medio complejo navegar esta clase., por lo que propongo un refactor de la misma. 
1) Existen muchos métodos que podrían reutilizarse, yo había creado uno que recibía listas de string e imprimía con un formato predefinido, podríamos re-evaluar el uso de ese método y que quede como el principal. 
2) La clase cumple responsabilidades que no debería tener, como obtener datos de player, o preguntar por citertas cosas. 
===========
Esto involucra crear más métodos a la clase "Calculator", tendríamos que darle más uso.

**Comment by JManuelLorenzo** [comment]
Estoy de acuerdo con vos Juan en que se estan repitiendo mucho las cosas de tal manera que manera que se podria refactorizar los metodos para ver cual utilizar en que casos pero como se podria hacer.
